
Table Services {
  ID int [pk, increment]
  ServiceName varchar
}

Table ConnectionStrings{
  ID int [pk, increment]
  Name varchar
  Value varchar
  ServiceID int
}

Ref: ConnectionStrings.ServiceID > Services.ID

Table BasicCredentials {
  ID int [pk, increment]
  ServiceID int
  Username varchar
  Email varchar
  Password varchar
}

Ref: BasicCredentials.ServiceID > Services.ID

Table OAuth2Tokens {
  ID int [pk, increment]
  ServiceID int
  Value varchar
}

Ref: OAuth2Tokens.ServiceID > Services.ID

Table APIKeys {
  ID int [pk, increment]
  ServiceID int
  ClientSecret varchar
  RefreshToken varchar
  AccessToken varchar
}

Ref: APIKeys.ServiceID > Services.ID
